services:
  ollama:
    image: ollama/ollama:latest
    profiles: ["with_ollama"]
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
      - ./scripts/download-models.sh:/entrypoint.sh
    healthcheck: 
      test: ["CMD", "curl", "-sf", "http://localhost:11434/api/tags"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]

    restart: unless-stopped

  multiagent:
    build: .
    container_name: multiagent
    profiles: ["core", "with_ollama"]
    ports:
      - "${ENV_SERVER_PORT:-8080}:8080"
    env_file: .env
    environment:
      - JAVA_OPTS=-Xms256m -Xmx768m
      - ENV_SERVER_PORT=${ENV_SERVER_PORT:-8080}
      - OLLAMA_BASE_URL=http://ollama:11434
      - LLM_TIMEOUT_MS=8000
      - DATA_DIR=/app/data
      - MAX_HISTORY_LINES=200
      - SUMMARIZATION_EVERY=40
    depends_on:
      - ollama
    restart: unless-stopped
volumes:
  ollama: